const longText = [
  'some text some text some text some text some text some text some text ',
  'some text some text some text some text some text some text some text ',
  'some text some text some text some text some text some text some text ',
  'some text some text some text some text some text some text some text ',
  'some text some text some text some text some text some text some text ',
  'some text some text some text some text some text some text some text ',
  'some text some text some text some text some text some text some text ',
  'some text some text some text some text some text some text some text ',
  'some text some text some text some text some text some text some text ',
  'some text some text some text some text some text some text some text ',
  'some text some text some text some text some text some text some text ',
  'some text some text some text some text some text some text some text ',
  'some text some text some text some text some text some text some text ',
  'some text some text some text some text some text some text some text ',
  'some text some text some text some text some text some text some text ',
  'some text some text some text some text some text some text some text ',
  'some text some text some text some text some text some text some text ',
  'some text some text some text some text some text some text some text ',
  'some text some text some text some text some text some text some text ',
  'some text some text some text some text some text some text some text ',
  'some text some text some text some text some text some text some text ',
  'some text some text some text some text some text some text some text ',
  'some text some text some text some text some text some text some text ',
  'some text some text some text some text some text some text some text ',
  'some text some text some text some text some text some text some text ',
  'some text some text some text some text some text some text some text ',
  'some text some text some text some text some text some text some text ',
  'some text some text some text some text some text some text some text ',
  'some text some text some text some text some text some text some text ',
  'some text some text some text some text some text some text some text ',
  'some text some text some text some text some text some text some text ',
  'some text some text some text some text some text some text some text ',
  'some text some text some text some text some text some text some text ',
  'some text some text some text some text some text some text some text ',
  'some text some text some text some text some text some text some text ',
  'some text some text some text some text some text some text some text ',
  'some text some text some text some text some text some text some text ',
].join('')

export default longText
